version: 2
jobs:
  build:
    docker:
      - image: drupal
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            composer install
      - run:
          name: install drupal coder
          command: | 
            composer global require drupal/coder	 
      - run:
          name: make phpcs global
          command: | 
            export PATH="$PATH:$HOME/.composer/vendor/bin"
      - run:   
          name: register drupal standart
          command: |
            phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
      - run:
          name: check installed standarts
          command: |
            phpcs -i
