
om_site_settings.site_settings_form:
  path: '/admin/config/site-settings'
  defaults:
    _form: '\Drupal\om_site_settings\Form\SiteSettingsForm'
    _title: 'Site Settings'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE

